
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J1
    - J2
    - J3
  gains:
    J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J4
  gains:
    J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1