obstacle_range: 2.5
raytrace_range: 4.0
robot_radius: 0.15
inflation_radius: 0.5
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: laser
laser: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}


